import { useState, useEffect, useRef } from "react";
import JsBarcode from "jsbarcode";
import { getAll, searchByField, updateItem, addItem } from "../services/firestoreService";
import { Badge, Button, SectionHeader, Toast } from "../components/ui/index.jsx";

const makeAwb = id =>
  `AWB${String(id).replace(/\D/g,"").slice(-6).padStart(6,"0")}${Math.floor(1000+Math.random()*9000)}`;

function BarcodeEl({ value, svgRef }) {
  useEffect(() => {
    if (!svgRef?.current || !value) return;
    JsBarcode(svgRef.current, value, {
      format:"CODE128", width:2, height:48,
      displayValue:false, margin:0, background:"transparent", lineColor:"currentColor",
    });
  }, [value]);
  return <svg ref={svgRef} style={{ width:"100%", maxWidth:360, color:"var(--text-primary)" }}/>;
}

const printLabel = (order, awb, paymentType, promiseDate, svgEl) => {
  let svgHtml = "";
  if (svgEl) {
    const c = svgEl.cloneNode(true);
    c.style.color="#000";
    c.querySelectorAll("rect,path").forEach(el=>{if(!el.getAttribute("fill")||el.getAttribute("fill")==="currentColor")el.setAttribute("fill","#000");});
    svgHtml = c.outerHTML;
  }
  const fields = [
    ["Order ID",              order.orderId],
    ["AWB No.",               awb],
    ["Payment Type",          paymentType],
    ["Customer Promise Date", promiseDate||"—"],
    ["Customer",              order.customerName||order.name],
    ["Address",               order.address||"—"],
    ["Vendor Name",           order.vendorName||"—"],
    ["Vendor GST No.",        order.vendorGst||"—"],
    ["SKU ID",                order.skuId],
    ["SKU Name",              order.productName],
    ["Quantity",              order.pickedQty??order.orderedQty??order.quantity],
    ["Batch No.",             order.batch||"—"],
    ["MFG Date",              order.mfgDate||"—"],
    ["Expiry Date",           order.expiryDate||"—"],
  ];
  const win = window.open("","_blank");
  win.document.write(`<!DOCTYPE html><html><head><title>Label — ${order.orderId}</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0;}body{font-family:Arial,sans-serif;color:#111;padding:28px;background:#fff;}
  .label{border:3px solid #111;border-radius:10px;padding:24px;max-width:580px;margin:0 auto;}
  .header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #111;padding-bottom:16px;margin-bottom:20px;}
  .title{font-size:24px;font-weight:900;letter-spacing:.12em;}.brand{font-size:11px;color:#666;margin-top:4px;}
  .awb-lbl{font-size:10px;text-transform:uppercase;letter-spacing:.1em;color:#888;text-align:right;}
  .awb-val{font-size:22px;font-weight:900;font-family:monospace;letter-spacing:.1em;text-align:right;}
  .fields{display:grid;grid-template-columns:1fr 1fr;gap:0;}
  .field{padding:8px 0;border-bottom:1px solid #eee;}
  .field:nth-child(odd){padding-right:18px;border-right:1px solid #eee;}
  .field:nth-child(even){padding-left:18px;}
  .fl{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#888;margin-bottom:2px;}
  .fv{font-size:13px;font-weight:700;word-break:break-word;}
  .barcode-wrap{text-align:center;margin-top:18px;padding:12px;border:1px solid #ddd;border-radius:6px;background:#f9f9f9;}
  .barcode-wrap svg{width:100%;max-width:360px;display:block;margin:0 auto;}
  .bnum{font-family:monospace;font-size:11px;color:#777;margin-top:6px;letter-spacing:.1em;}
  .footer{margin-top:14px;font-size:10px;color:#bbb;text-align:center;}
  @media print{body{padding:0;}}
</style></head><body><div class="label">
  <div class="header">
    <div><div class="title">SHIPPING LABEL</div><div class="brand">MIDC IMS · Eduspark</div></div>
    <div><div class="awb-lbl">AWB No.</div><div class="awb-val">${awb}</div></div>
  </div>
  <div class="fields">${fields.map(([l,v])=>`<div class="field"><div class="fl">${l}</div><div class="fv">${v??'—'}</div></div>`).join("")}</div>
  <div class="barcode-wrap">
    ${svgHtml||`<div style="font-family:monospace;font-size:26px;letter-spacing:.15em">||| ${order.orderId} |||</div>`}
    <div class="bnum">${order.orderId}</div>
  </div>
  <div class="footer">Generated by MIDC IMS · ${new Date().toLocaleString()}</div>
</div><script>window.onload=()=>{window.print();}</script></body></html>`);
  win.document.close();
};

export default function PackingPage({ packOrder, clearPackOrder, goToReturns }) {
  const [tab, setTab]               = useState("Pack Orders");
  const [packList, setPackList]     = useState([]);
  const [loading, setLoading]       = useState(true);
  const [activeOrder, setActiveOrder] = useState(null);
  const [awbNumber, setAwbNumber]   = useState("");
  const [paymentType, setPaymentType] = useState("Prepaid");
  const [promiseDate, setPromiseDate] = useState("");
  // QC label state
  const [qcResult, setQcResult]     = useState(null); // "Pass" | "Fail"
  const [toast, setToast]           = useState(null);
  const barcodeRef = useRef();

  const load = async () => {
    setLoading(true);
    const picked = await getAll("pickingdata");
    setPackList(picked.filter(p => p.status==="Picked" || p.status==="Packing"));
    setLoading(false);
  };
  useEffect(() => { load(); }, []);

  const enrichOrder = async (order) => {
    const [customers, vendors] = await Promise.all([
      searchByField("customers","orderId",order.orderId),
      getAll("vendors"),
    ]);
    const customer = customers[0] || {};
    const vendor   = vendors.find(v => v.skuId===order.skuId) || {};

    // Fetch batch/mfg/expiry from inventory
    const invItems = await searchByField("inventory","skuId",order.skuId);
    const inv = invItems[0] || {};

    return {
      ...order,
      address:     customer.address  || "—",
      customerDate: customer.createdAt ? new Date(customer.createdAt).toLocaleDateString() : "—",
      vendorName:  vendor.vendorName || "—",
      vendorGst:   vendor.gstNo      || "—",
      batch:       inv.batch         || "—",
      mfgDate:     inv.mfgDate       || "—",
      expiryDate:  inv.expiryDate    || "—",
    };
  };

  useEffect(() => {
    if (packOrder) {
      enrichOrder(packOrder).then(enriched => {
        setActiveOrder(enriched);
        setAwbNumber(makeAwb(enriched.orderId));
        setQcResult(null);
        setPaymentType("Prepaid");
        setPromiseDate("");
        setTab("Packing");
        clearPackOrder();
      });
    }
  }, [packOrder]);

  const handleStartPacking = async (order) => {
    const enriched = await enrichOrder(order);
    setActiveOrder(enriched);
    setAwbNumber(makeAwb(enriched.orderId));
    setQcResult(null);
    setPaymentType("Prepaid");
    setPromiseDate("");
    setTab("Packing");
  };

  // QC Pass → mark shipped
  const handleQCPass = async () => {
    setQcResult("Pass");
  };

  const handleShipped = async () => {
    if (!activeOrder) return;
    const [records, customers] = await Promise.all([
      searchByField("pickingdata","orderId",activeOrder.orderId),
      searchByField("customers","orderId",activeOrder.orderId),
    ]);
    for (const r of records)   await updateItem("pickingdata",r.id,{status:"Shipped"});
    for (const c of customers) await updateItem("customers",c.id,{status:"Shipped"});
    setToast({ msg:`Order ${activeOrder.orderId} shipped`, type:"success" });
    setTimeout(() => {
      goToReturns({...activeOrder, status:"Shipped"});
      setActiveOrder(null);
      setQcResult(null);
      setTab("Pack Orders");
      load();
    }, 1200);
  };

  // QC Fail → move to customer return queue
  const handleQCFail = async () => {
    setQcResult("Fail");
    if (!activeOrder) return;
    await addItem("customerreturns", {
      orderId:     activeOrder.orderId,
      customerName: activeOrder.customerName,
      skuId:       activeOrder.skuId,
      productName: activeOrder.productName,
      qty:         activeOrder.pickedQty || activeOrder.orderedQty,
      reason:      "QC Failed during packing",
      status:      "Pending",
      createdAt:   new Date().toISOString(),
    });
    const customers = await searchByField("customers","orderId",activeOrder.orderId);
    for (const c of customers) await updateItem("customers",c.id,{status:"In Transit"});
    setToast({ msg:`QC Failed — ${activeOrder.orderId} moved to Customer Return Queue`, type:"error" });
  };

  const labelFields = activeOrder ? [
    ["Order ID",              activeOrder.orderId],
    ["AWB No.",               awbNumber],
    ["Payment Type",          paymentType],
    ["Customer Promise Date", promiseDate||"—"],
    ["Customer",              activeOrder.customerName||activeOrder.name],
    ["Address",               activeOrder.address],
    ["Vendor Name",           activeOrder.vendorName],
    ["Vendor GST No.",        activeOrder.vendorGst],
    ["SKU ID",                activeOrder.skuId],
    ["SKU Name",              activeOrder.productName],
    ["Quantity",              activeOrder.pickedQty??activeOrder.orderedQty],
    ["Batch No.",             activeOrder.batch],
    ["MFG Date",              activeOrder.mfgDate],
    ["Expiry Date",           activeOrder.expiryDate],
  ] : [];

  return (
    <div>
      {toast && <Toast message={toast.msg} type={toast.type} onClose={()=>setToast(null)}/>}
      <SectionHeader title="Packing" subtitle="Pack, QC label & dispatch orders"/>
      <div className="ims-tab-bar">
        {["Pack Orders","Packing"].map(t=>(
          <button key={t} className={`ims-tab${tab===t?" active":""}`} onClick={()=>setTab(t)}>{t}</button>
        ))}
      </div>

      {/* ── Pack Orders list ── */}
      {tab==="Pack Orders" && (
        <div style={{display:"flex",flexDirection:"column",gap:16}}>
          <Button variant="ghost" onClick={load} style={{width:"fit-content"}}>↻ Refresh</Button>
          {loading
            ? <div style={{display:"flex",alignItems:"center",justifyContent:"center",padding:64}}>
                <div className="spin" style={{width:24,height:24,border:"2px solid var(--border)",borderTopColor:"var(--accent)",borderRadius:"50%"}}/>
              </div>
            : <div className="ims-table-wrap">
                <table className="ims-table">
                  <thead><tr>{["Order ID","Customer","SKU ID","Product","Ordered Qty","Pick Qty","Status","Action"].map(c=><th key={c}>{c}</th>)}</tr></thead>
                  <tbody>
                    {packList.length===0
                      ? <tr><td colSpan={8} className="t-muted" style={{padding:"48px 16px",textAlign:"center"}}>No orders ready to pack</td></tr>
                      : packList.map((r,i)=>(
                        <tr key={i}>
                          <td className="mono" style={{padding:"12px 16px"}}><span className="t-accent">{r.orderId}</span></td>
                          <td style={{padding:"12px 16px",fontWeight:600}}>{r.customerName}</td>
                          <td className="mono" style={{padding:"12px 16px"}}>{r.skuId}</td>
                          <td style={{padding:"12px 16px"}}>{r.productName}</td>
                          <td style={{padding:"12px 16px"}}>{r.orderedQty}</td>
                          <td style={{padding:"12px 16px"}}><span className="t-success" style={{fontWeight:700}}>{r.pickedQty}</span></td>
                          <td style={{padding:"12px 16px"}}>
                            <Badge color={r.status==="Shipped"?"green":r.status==="Packing"?"violet":"cyan"}>{r.status}</Badge>
                          </td>
                          <td style={{padding:"12px 16px"}}>
                            {r.status!=="Shipped" &&
                              <Button variant="primary" onClick={()=>handleStartPacking(r)}>Start Packing</Button>}
                          </td>
                        </tr>
                      ))
                    }
                  </tbody>
                </table>
              </div>
          }
        </div>
      )}

      {/* ── Packing / QC Label ── */}
      {tab==="Packing" && (
        <div style={{display:"flex",flexDirection:"column",gap:20,maxWidth:680}}>
          {!activeOrder
            ? <div className="ims-panel" style={{textAlign:"center"}}>
                <p className="t-muted" style={{marginBottom:16}}>No order selected. Go to Pack Orders and click Start Packing.</p>
                <Button variant="ghost" onClick={()=>setTab("Pack Orders")}>← Back</Button>
              </div>
            : <>
                {/* Editable fields */}
                <div className="ims-panel" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
                  <div style={{display:"flex",flexDirection:"column",gap:6}}>
                    <label className="ims-label">Payment Type</label>
                    <select className="ims-input" value={paymentType} onChange={e=>setPaymentType(e.target.value)}>
                      <option>Prepaid</option>
                      <option>Cash on Delivery</option>
                      <option>Credit</option>
                    </select>
                  </div>
                  <div style={{display:"flex",flexDirection:"column",gap:6}}>
                    <label className="ims-label">Customer Promise Date</label>
                    <input type="date" className="ims-input" value={promiseDate} onChange={e=>setPromiseDate(e.target.value)}/>
                  </div>
                </div>

                {/* Shipping Label */}
                <div className="ims-card" style={{padding:28,borderRadius:16}}>
                  <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",borderBottom:"2px solid var(--border)",paddingBottom:18,marginBottom:20}}>
                    <div>
                      <div className="gradient-text" style={{fontSize:22,fontWeight:900,letterSpacing:"0.12em",fontFamily:"'Syne',sans-serif"}}>SHIPPING LABEL</div>
                      <div className="t-muted" style={{fontSize:11,marginTop:3}}>MIDC IMS — Eduspark</div>
                    </div>
                    <div style={{textAlign:"right"}}>
                      <div className="t-muted" style={{fontSize:10,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.08em",marginBottom:4}}>AWB No.</div>
                      <div className="t-accent" style={{fontSize:20,fontWeight:900,fontFamily:"monospace",letterSpacing:"0.1em"}}>{awbNumber}</div>
                    </div>
                  </div>
                  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:0}}>
                    {labelFields.map(([l,v],i)=>(
                      <div key={l} style={{padding:"9px 0",borderBottom:"1px solid var(--border)",
                        ...(i%2===0?{paddingRight:20,borderRight:"1px solid var(--border)"}:{paddingLeft:20})}}>
                        <div className="t-muted" style={{fontSize:10,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.08em",marginBottom:3}}>{l}</div>
                        <div className="t-primary" style={{fontSize:13,fontWeight:700,wordBreak:"break-word"}}>{v??'—'}</div>
                      </div>
                    ))}
                  </div>
                  {/* Barcode */}
                  <div style={{marginTop:20,padding:"14px 16px",borderRadius:8,border:"1px solid var(--border)",background:"var(--bg-elevated)",textAlign:"center"}}>
                    <BarcodeEl value={activeOrder.orderId} svgRef={barcodeRef}/>
                    <div className="t-secondary" style={{fontSize:12,marginTop:6,fontFamily:"monospace",letterSpacing:"0.08em"}}>{activeOrder.orderId}</div>
                  </div>
                </div>

                {/* QC section */}
                <div className="ims-panel">
                  <p className="ims-section-title">Packing QC Check</p>
                  {qcResult
                    ? qcResult==="Pass"
                      ? <div className="ims-success-box" style={{marginBottom:16}}>
                          <p className="t-success" style={{fontWeight:700,margin:"0 0 4px"}}>✓ QC Passed — Ready to ship</p>
                          <p className="t-muted" style={{fontSize:12,margin:0}}>Click Mark as Shipped to dispatch</p>
                        </div>
                      : <div className="ims-elevated" style={{marginBottom:16,padding:"14px 18px",border:"1px solid var(--badge-red-br)",borderRadius:8}}>
                          <p className="t-danger" style={{fontWeight:700,margin:"0 0 4px"}}>✕ QC Failed — Moved to Customer Return Queue</p>
                          <p className="t-muted"  style={{fontSize:12,margin:0}}>Order status reset to In Transit</p>
                        </div>
                    : <div style={{display:"flex",gap:12}}>
                        <Button variant="success" onClick={handleQCPass}>✓ QC Pass</Button>
                        <Button variant="danger"  onClick={handleQCFail}>✕ QC Fail</Button>
                      </div>
                  }
                </div>

                {/* Actions */}
                <div style={{display:"flex",gap:12}}>
                  <Button onClick={()=>printLabel(activeOrder,awbNumber,paymentType,promiseDate,barcodeRef.current)} variant="ghost">
                    🖨 Export / Print Label
                  </Button>
                  {qcResult==="Pass" &&
                    <Button onClick={handleShipped} variant="success">✓ Mark as Shipped</Button>}
                  <Button onClick={()=>{setTab("Pack Orders");setActiveOrder(null);setQcResult(null);}} variant="ghost">
                    ← Back
                  </Button>
                </div>
                <div className="ims-accent-box">
                  <p className="t-secondary" style={{margin:0,fontSize:12}}>
                    <strong>QC Pass</strong> → Print label → Mark as Shipped ·
                    <strong> QC Fail</strong> → Order moved to Customer Return Queue
                  </p>
                </div>
              </>
          }
        </div>
      )}
    </div>
  );
}
